console.log("1-menu")
console.log("2-cadastro de aluno")
console.log("3-listar todos os alunos")
console.log("4-listar aluno em específico")
console.log("5-atualizar aluno")
console.log("6-excluir aluno")
console.log("7-media")
console.log("8-main")
console.log("")
console.log("Id:")
console.log("Nome:")
console.log("Matricula:")
console.log("Idade:")
console.log("nota:")